@IsTest 
private class LoggerTest {
    @IsTest 
    static void shouldLogIfMeetsThreshold() {
        Assert.fail('You still need to build this test');
    }
    
    @IsTest 
    static void shouldLogIfExceedsThreshold() {
        Assert.fail('You still need to build this test');        
    }

    @IsTest 
    static void shouldNotLogIfDisabled() {
        Assert.fail('You still need to build this test');
    }

    @IsTest
    static void shouldNotLogIfBelowThreshold() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldNotLogIfThresholdIsNone() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldPublishViaSynchronousDml() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldPublishViaPlatformEvent() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldPublishViaDefaultMethod() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldIncrementOrdinal() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldLogWithApexClass() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldLogWithRelatedRecord() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldLogWithSource() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldLogUsingShorthandOverloads() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldLogRegardlessOfUserAccess() {
        Assert.fail('You still need to build this test');
    }
}